version: '3.7'
services:
  quasar:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '9000:9000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    env_file:
      - './.env'
    restart: 'unless-stopped'
    command: 'npm run dev'

